version: '3'
services:
  exam_app_server:
    container_name: examapp_server
    image: pankiev/examapp
    ports:
      - 80:80
    depends_on:
      - exam_app_db
    restart: on-failure
    networks:
      - exam_app_net


  exam_app_db:
    container_name: exam_app_db
    image: mysql:5.7.15
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=exam_app
    networks:
      - exam_app_net

networks:
  exam_app_net:
